<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;
use App\Models\saspro_indikator_new;
use Illuminate\Support\Facades\DB;
class indikator_saspro_new extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('indikator_saspro')->insert([
            [
                'kode_sastra' => '1',
                'kode_saspro' => '1.1',
                'kode_indikator' => '1.1-1',
                'nama_indikator' => 'Indeks kepuasan layanan publik bidang penegakan hukum',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '2',
                'kode_saspro' => '2.1',
                'kode_indikator' => '2.1-1',
                'nama_indikator' => 'Tingkat utilisasi sarana dan prasarana dalam mendukung penegakan dan pelayanan hukum di Kejaksaan RI',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '2',
                'kode_saspro' => '2.2',
                'kode_indikator' => '2.2-1',
                'nama_indikator' => 'Tingkat keberhasilan penanganan perkara Tindak Pidana Umum yang diproses hingga pra penuntutan',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '2',
                'kode_saspro' => '2.2',
                'kode_indikator' => '2.2-2',
                'nama_indikator' => 'Tingkat keberhasilan penanganan perkara Tindak Pidana Umum yang diproses hingga penuntutan',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '2',
                'kode_saspro' => '2.2',
                'kode_indikator' => '2.2-3',
                'nama_indikator' => 'Tingkat keberhasilan penanganan perkara tindak Pidana Umum yang in kracht van gewisjde (berkekuatan hukum tetap) dan telah dieksekusi',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '2',
                'kode_saspro' => '2.3',
                'kode_indikator' => '2.3-1',
                'nama_indikator' => 'Persentase penanganan perkara melalui mediasi penal, diskresi penuntutan, dan denda damai',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '2',
                'kode_saspro' => '2.4',
                'kode_indikator' => '2.4-1',
                'nama_indikator' => 'Tingkat keberhasilan penanganan perkara tindak pidana korupsi dan TPPU',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '2',
                'kode_saspro' => '2.4',
                'kode_indikator' => '2.4-2',
                'nama_indikator' => 'Tingkat keberhasilan penanganan perkara tindak pidana perpajakan dan TPPU',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '2',
                'kode_saspro' => '2.4',
                'kode_indikator' => '2.4-3',
                'nama_indikator' => 'Tingkat keberhasilan penanganan perkara tindak pidana kepabeanan dan TPPU',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '2',
                'kode_saspro' => '2.4',
                'kode_indikator' => '2.4-4',
                'nama_indikator' => 'Tingkat keberhasilan penanganan perkara tindak pidana cukai dan TPPU',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '2',
                'kode_saspro' => '2.4',
                'kode_indikator' => '2.4-5',
                'nama_indikator' => 'Tingkat keberhasilan penanganan perkara tindak pidana yang menyebabkan kerugian perekonomian negara dan TPPU',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '2',
                'kode_saspro' => '2.4',
                'kode_indikator' => '2.4-6',
                'nama_indikator' => 'Tingkat keberhasilan penanganan perkara pelanggaran HAM Berat',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '2',
                'kode_saspro' => '2.4',
                'kode_indikator' => '2.4-7',
                'nama_indikator' => 'Tingkat keberhasilan pengendalian operasi dalam penyelesaian penanganan perkara tindak pidana khusus',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '2',
                'kode_saspro' => '2.5',
                'kode_indikator' => '2.5-1',
                'nama_indikator' => 'Tingkat keberhasilan penyelamatan dan pengembalian kerugian negara dalam penanganan perkara tindak pidana korupsi dan TPPU',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '2',
                'kode_saspro' => '2.5',
                'kode_indikator' => '2.5-2',
                'nama_indikator' => 'Tingkat keberhasilan pembayaran denda dalam penanganan perkara tindak pidana khusus lainnya dan TPPU (Kepabeanan, Perpajakan, Cukai, tindak Pidana yang menyebabkan kerugian perekonomian negara)',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '2',
                'kode_saspro' => '2.6',
                'kode_indikator' => '2.6-1',
                'nama_indikator' => 'Tingkat keberhasilan penanganan perkara koneksitas pada tahap penyelidikan',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '2',
                'kode_saspro' => '2.6',
                'kode_indikator' => '2.6-2',
                'nama_indikator' => 'Tingkat keberhasilan penanganan perkara koneksitas pada tahap penyidikan',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '2',
                'kode_saspro' => '2.6',
                'kode_indikator' => '2.6-3',
                'nama_indikator' => 'Tingkat keberhasilan penanganan perkara koneksitas pada tahap penuntutan',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '2',
                'kode_saspro' => '2.6',
                'kode_indikator' => '2.6-4',
                'nama_indikator' => 'Tingkat keberhasilan penanganan perkara koneksitas yang telah dieksekusi',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '2',
                'kode_saspro' => '2.6',
                'kode_indikator' => '2.6-5',
                'nama_indikator' => 'Tingkat keberhasilan pengembalian Kerugian Negara Perkara Koneksitas yang dilimpahkan ke peradilan umum',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '2',
                'kode_saspro' => '2.7',
                'kode_indikator' => '2.7-1',
                'nama_indikator' => 'Tingkat keberhasilan pelaksanaan Kegiatan Koordinasi Teknis (Assurance, Consultative, Pencegahan Fraud, Monitoring dan Evaluasi dan Pelaporan) Tahap Penindakan',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '2',
                'kode_saspro' => '2.7',
                'kode_indikator' => '2.7-2',
                'nama_indikator' => 'Tingkat keberhasilan pelaksanaan Kegiatan Koordinasi Teknis (Assurance, Consultative, Pencegahan Fraud, Monitoring dan Evaluasi dan Pelaporan) Tahap Penuntutan',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '2',
                'kode_saspro' => '2.7',
                'kode_indikator' => '2.7-3',
                'nama_indikator' => 'Tingkat keberhasilan pelaksanaan Kegiatan Koordinasi Teknis (Assurance, Consultative, Pencegahan Fraud, Monitoring dan Evaluasi dan Pelaporan) Tahap Eksekusi, Upaya Hukum Luar Biasa dan Eksaminasi',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '2',
                'kode_saspro' => '2.8',
                'kode_indikator' => '2.8-1',
                'nama_indikator' => 'Tingkat Pemahaman Hukum Masyarakat atas Materi Sosialisasi Hukum',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '2',
                'kode_saspro' => '2.8',
                'kode_indikator' => '2.8-2',
                'nama_indikator' => 'Tingkat Kepuasan Pemangku Kepentingan terhadap Layanan Lukumpenkum',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '2',
                'kode_saspro' => '2.9',
                'kode_indikator' => '2.9-1',
                'nama_indikator' => 'Tingkat efektivitas intelijen penegakan hukum Kejaksaan',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '2',
                'kode_saspro' => '2.10',
                'kode_indikator' => '2.10-1',
                'nama_indikator' => 'Tingkat keberhasilan kegiatan penelusuran aset',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '2',
                'kode_saspro' => '2.10',
                'kode_indikator' => '2.10-2',
                'nama_indikator' => 'Tingkat keberhasilan perampasan aset hasil tindak pidana',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '2',
                'kode_saspro' => '2.10',
                'kode_indikator' => '2.10-3',
                'nama_indikator' => 'Tingkat keberhasilan pemulihan aset hasil tindak pidana',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '2',
                'kode_saspro' => '2.11',
                'kode_indikator' => '2.11-1',
                'nama_indikator' => 'Tingkat efektivitas pengelolaan Rupbasan',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '2',
                'kode_saspro' => '2.11',
                'kode_indikator' => '2.11-2',
                'nama_indikator' => 'Tingkat efektivitas penyelesaian penyelamatan aset negara',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '2',
                'kode_saspro' => '2.11',
                'kode_indikator' => '2.11-3',
                'nama_indikator' => 'Tingkat efektivitas pengelolaan data aset negara berbasis teknologi',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '2',
                'kode_saspro' => '2.12',
                'kode_indikator' => '2.12-1',
                'nama_indikator' => 'Tingkat kualitas penanganan perkara yang terekam dalam Case Management System',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '3',
                'kode_saspro' => '3.1',
                'kode_indikator' => '3.1-1',
                'nama_indikator' => 'Tingkat penjaminan kualitas pengajuan pendapat teknis hukum untuk permohonan kasasi lingkup peradilan umum, TUN, agama, dan militer',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '3',
                'kode_saspro' => '3.2',
                'kode_indikator' => '3.2-1',
                'nama_indikator' => 'Indeks Persepsi atas pelayanan hukum',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '3',
                'kode_saspro' => '3.3',
                'kode_indikator' => '3.3-1',
                'nama_indikator' => 'Tingkat keberhasilan penyelamatan keuangan negara melalui jalur perdata',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '3',
                'kode_saspro' => '3.3',
                'kode_indikator' => '3.3-2',
                'nama_indikator' => 'Tingkat keberhasilan pemulihan keuangan negara melalui jalur perdata',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '3',
                'kode_saspro' => '3.4',
                'kode_indikator' => '3.4-1',
                'nama_indikator' => 'Tingkat keberhasilan penanganan perkara perdata melalui jalur litigasi',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '3',
                'kode_saspro' => '3.4',
                'kode_indikator' => '3.4-2',
                'nama_indikator' => 'Tingkat keberhasilan penanganan perkara perdata melalui jalur non-litigasi',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '3',
                'kode_saspro' => '3.4',
                'kode_indikator' => '3.4-3',
                'nama_indikator' => 'Tingkat keberhasilan penanganan perkara tata usaha negara melalui jalur litigasi',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '3',
                'kode_saspro' => '3.5',
                'kode_indikator' => '3.5-1',
                'nama_indikator' => 'Indeks kepuasan layanan Publik bidang hukum (Layanan hukum gratis, konsultasi hukum, bantuan hukum, pendampingan hukum, dan penyuluhan hukum)',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '4',
                'kode_saspro' => '4.1',
                'kode_indikator' => '4.1-1',
                'nama_indikator' => 'Nilai SAKIP Kejaksaan RI',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '4',
                'kode_saspro' => '4.2',
                'kode_indikator' => '4.2-1',
                'nama_indikator' => 'Opini BPK',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '4',
                'kode_saspro' => '4.3',
                'kode_indikator' => '4.3-1',
                'nama_indikator' => 'Nilai Maturitas Penyelenggaraan SPIP secara terintegrasi pada Kejaksaan RI',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '4',
                'kode_saspro' => '4.4',
                'kode_indikator' => '4.4-1',
                'nama_indikator' => 'Nilai Kinerja Anggaran Kejaksaan RI',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '4',
                'kode_saspro' => '4.5',
                'kode_indikator' => '4.5-1',
                'nama_indikator' => 'Indeks Pengelolaan Aset Kejaksaan RI',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '4',
                'kode_saspro' => '4.5',
                'kode_indikator' => '4.5-2',
                'nama_indikator' => 'Indeks Tata Kelola Pengadaan Kejaksaan RI',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '4',
                'kode_saspro' => '4.6',
                'kode_indikator' => '4.6-1',
                'nama_indikator' => 'Nilai Evaluasi Kelembagaan Kejaksaan RI',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '4',
                'kode_saspro' => '4.6',
                'kode_indikator' => '4.6-2',
                'nama_indikator' => 'Tingkat kepatuhan satuan kerja terhadap standar operasional prosedur',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '4',
                'kode_saspro' => '4.7',
                'kode_indikator' => '4.7-1',
                'nama_indikator' => 'Indeks Kualitas Kebijakan Kejaksaan RI',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '4',
                'kode_saspro' => '4.7',
                'kode_indikator' => '4.7-2',
                'nama_indikator' => 'Indeks Reformasi Hukum pada Kejaksaan RI',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '4',
                'kode_saspro' => '4.8',
                'kode_indikator' => '4.8-1',
                'nama_indikator' => 'Indeks Sistem Merit Kejaksaan RI',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '4',
                'kode_saspro' => '4.8',
                'kode_indikator' => '4.8-2',
                'nama_indikator' => 'Persentase kecukupan, kesesuaian, dan pengembangan SDM Kejaksaan RI',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '4',
                'kode_saspro' => '4.8',
                'kode_indikator' => '4.8-3',
                'nama_indikator' => 'Indeks Profesionalitas SDM Kejaksaan RI',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '4',
                'kode_saspro' => '4.9',
                'kode_indikator' => '4.9-1',
                'nama_indikator' => 'Indeks Kepuasan pengguna hasil pendidikan dan pelatihan',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '4',
                'kode_saspro' => '4.10',
                'kode_indikator' => '4.10-1',
                'nama_indikator' => 'Indeks kepuasan layanan dukungan internal manajemen Kejaksaan RI',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '4',
                'kode_saspro' => '4.10',
                'kode_indikator' => '4.10-2',
                'nama_indikator' => 'Tingkat kepuasan Stakeholder terhadap Rumah Sakit Adhyaksa, Klinik Adhyaksa, dan Fasilitas Kesehatan Yustisial lainnya',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '4',
                'kode_saspro' => '4.11',
                'kode_indikator' => '4.11-1',
                'nama_indikator' => 'Indeks kesesuaian kompetensi (competency fit index) aparatur Kejaksaan RI',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '4',
                'kode_saspro' => '4.11',
                'kode_indikator' => '4.11-2',
                'nama_indikator' => 'Persentase aparatur yang memiliki sertifikasi kompetensi sesuai jabatan',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '4',
                'kode_saspro' => '4.12',
                'kode_indikator' => '4.12-1',
                'nama_indikator' => 'Indeks survei perilaku Integritas Kejaksaan RI',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '4',
                'kode_saspro' => '4.13',
                'kode_indikator' => '4.13-1',
                'nama_indikator' => 'Indeks kepuasan satker Kejaksaan atas layanan hukum',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '4',
                'kode_saspro' => '4.13',
                'kode_indikator' => '4.13-2',
                'nama_indikator' => 'Indeks kepuasan institusi mitra luar negeri terhadap kualitas kerja sama kelembagaan Kejaksaan RI',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '4',
                'kode_saspro' => '4.14',
                'kode_indikator' => '4.14-1',
                'nama_indikator' => 'Tingkat kepatuhan terhadap implementasi Zona Integritas',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '4',
                'kode_saspro' => '4.15',
                'kode_indikator' => '4.15-1',
                'nama_indikator' => 'Persentase digitalisasi proses bisnis inti Kejaksaan RI',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
            [
                'kode_sastra' => '4',
                'kode_saspro' => '4.16',
                'kode_indikator' => '4.16-1',
                'nama_indikator' => 'Tingkat utilisasi sarana dan prasarana Kejaksaan RI',
                //'created_at' => now(),
   //             'updated_at' => now(),
            ],
        ]);
    }   
}