<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\saspro_new;
use Illuminate\Support\Facades\DB;
class saspro_new_seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Data dari file CSV yang Anda unggah
        // PERHATIAN: 'id_sastra' diset default ke '1'. Sesuaikan dengan data Sastra Anda.
      DB::table('sakip_saspro_new')->insert([
           [
                'id_sastra' => '1',
                'id_saspro' => '1.1',
                'nama_saspro' => 'Meningkatnya Kualitas Layanan Publik bidang penegakan hukum',
                'deskripsi' => '.',
            //    'created_at' => now(),
             //   'updated_at' => now(),
            ],
            [
                'id_sastra' => '2',
                'id_saspro' => '2.1',
                'nama_saspro' => 'Meningkatnya efektivitas pemanfaatan sarana dan prasarana dalam mendukung penegakan dan pelayanan hukum di Kejaksaan RI',
                'deskripsi' => '.',
            //    'created_at' => now(),
             //   'updated_at' => now(),
            ],
            [
                'id_sastra' => '2',
                'id_saspro' => '2.2',
                'nama_saspro' => 'Meningkatnya keberhasilan penyelesaian Perkara Tindak Pidana Umum',
                'deskripsi' => '.',
            //    'created_at' => now(),
             //   'updated_at' => now(),
            ],
            [
                'id_sastra' => '2',
                'id_saspro' => '2.3',
                'nama_saspro' => 'Meningkatnya penegakan hukum yang yang adil, humanis, proporsional, dan efisien',
                'deskripsi' => '.',
            //    'created_at' => now(),
             //   'updated_at' => now(),
            ],
            [
                'id_sastra' => '2',
                'id_saspro' => '2.4',
                'nama_saspro' => 'Meningkatnya keberhasilan penanganan perkara tindak pidana korupsi, tindak pidana perpajakan, tindak pidana kepabeanan, tindak pidana cukai, tindak pidana yang menyebabkan kerugian perekonomian negara, dan TPPU serta pelanggaran HAM Berat secara transparan, akuntabel dan profesional',
                'deskripsi' => '.',
            //    'created_at' => now(),
             //   'updated_at' => now(),
            ],
            [
                'id_sastra' => '2',
                'id_saspro' => '2.5',
                'nama_saspro' => 'Meningkatnya keberhasilan pengembalian kerugian negara dalam penanganan perkara tindak pidana khusus',
                'deskripsi' => '.',
            //    'created_at' => now(),
             //   'updated_at' => now(),
            ],
            [
                'id_sastra' => '2',
                'id_saspro' => '2.6',
                'nama_saspro' => 'Meningkatnnya keberhasilan penanganan perkara koneksitas tindak pidana korupsi, tindak pidana pencucian uang, dan tindak pidana lain',
                'deskripsi' => '.',
            //    'created_at' => now(),
             //   'updated_at' => now(),
            ],
            [
                'id_sastra' => '2',
                'id_saspro' => '2.7',
                'nama_saspro' => 'Meningkatnnya keberhasilan pelaksanaan koordinasi teknis penuntutan yang dilakukan oleh oditurat militer',
                'deskripsi' => '.',
            //    'created_at' => now(),
             //   'updated_at' => now(),
            ],
            [
                'id_sastra' => '2',
                'id_saspro' => '2.8',
                'nama_saspro' => 'Meningkatnya Pemahaman Hukum Masyarakat yang Memuaskan Pemangku Kepentingan',
                'deskripsi' => '.',
            //    'created_at' => now(),
             //   'updated_at' => now(),
            ],
            [
                'id_sastra' => '2',
                'id_saspro' => '2.9',
                'nama_saspro' => 'Meningkatnya efektivitas intelijen penegakan hukum Kejaksaan',
                'deskripsi' => '.',
            //    'created_at' => now(),
             //   'updated_at' => now(),
            ],
            [
                'id_sastra' => '2',
                'id_saspro' => '2.10',
                'nama_saspro' => 'Terselenggaranya pemulihan aset yang terintegrasi',
                'deskripsi' => '.',
            //    'created_at' => now(),
             //   'updated_at' => now(),
            ],
            [
                'id_sastra' => '2',
                'id_saspro' => '2.11',
                'nama_saspro' => 'Terwujudnya pengelolaan aset tindak pidana yang transparan, akuntabel, dan modern',
                'deskripsi' => '.',
            //    'created_at' => now(),
             //   'updated_at' => now(),
            ],
            [
                'id_sastra' => '2',
                'id_saspro' => '2.12',
                'nama_saspro' => 'Meningkatnya kualitas sistem penuntutan yang terintegrasi dan transparan',
                'deskripsi' => '.',
            //    'created_at' => now(),
             //   'updated_at' => now(),
            ],
            [
                'id_sastra' => '3',
                'id_saspro' => '3.1',
                'nama_saspro' => 'Meningkatnya kualitas pelaksanaan Advocaat Generaal dan Jaksa Pengacara Negara',
                'deskripsi' => '.',
            //    'created_at' => now(),
             //   'updated_at' => now(),
            ],
            [
                'id_sastra' => '3',
                'id_saspro' => '3.2',
                'nama_saspro' => 'Meningkatnya efektivitas pelayanan hukum dalam rangka pelaksanaan fungsi Jaksa Pengacara Negara',
                'deskripsi' => '.',
            //    'created_at' => now(),
             //   'updated_at' => now(),
            ],
            [
                'id_sastra' => '3',
                'id_saspro' => '3.3',
                'nama_saspro' => 'Meningkatnya keberhasilan penyelamatan dan pemulihan keuangan negara melalui jalur perdata',
                'deskripsi' => '.',
            //    'created_at' => now(),
             //   'updated_at' => now(),
            ],
            [
                'id_sastra' => '3',
                'id_saspro' => '3.4',
                'nama_saspro' => 'Meningkatnya keberhasilan penanganan Perkara Perdata dan Tata Usaha Negara secara transparan, akuntabel, dan profesional',
                'deskripsi' => '.',
            //    'created_at' => now(),
             //   'updated_at' => now(),
            ],
            [
                'id_sastra' => '3',
                'id_saspro' => '3.5',
                'nama_saspro' => 'Meningkatnya Kualitas Layanan Publik bidang hukum',
                'deskripsi' => '.',
            //    'created_at' => now(),
             //   'updated_at' => now(),
            ],
            [
                'id_sastra' => '4',
                'id_saspro' => '4.1',
                'nama_saspro' => 'Meningkatnya akuntabilitas kinerja Kejaksaan RI',
                'deskripsi' => '.',
            //    'created_at' => now(),
             //   'updated_at' => now(),
            ],
            [
                'id_sastra' => '4',
                'id_saspro' => '4.2',
                'nama_saspro' => 'Meningkatnya akuntabilitas keuangan Kejaksaan RI',
                'deskripsi' => '.',
            //    'created_at' => now(),
             //   'updated_at' => now(),
            ],
            [
                'id_sastra' => '4',
                'id_saspro' => '4.3',
                'nama_saspro' => 'Menguatnya pengendalian internal pada Kejaksaan RI',
                'deskripsi' => '.',
            //    'created_at' => now(),
             //   'updated_at' => now(),
            ],
            [
                'id_sastra' => '4',
                'id_saspro' => '4.4',
                'nama_saspro' => 'Meningkatnya efisiensi dan efektivitas penggunaan anggaran Kejaksaan RI',
                'deskripsi' => '.',
            //    'created_at' => now(),
             //   'updated_at' => now(),
            ],
            [
                'id_sastra' => '4',
                'id_saspro' => '4.5',
                'nama_saspro' => 'Meningkatnya kualitas tata kelola aset dan pengadaan Kejaksaan RI',
                'deskripsi' => '.',
            //    'created_at' => now(),
             //   'updated_at' => now(),
            ],
            [
                'id_sastra' => '4',
                'id_saspro' => '4.6',
                'nama_saspro' => 'Meningkatnya kapasitas kelembagaan dan ketatalaksanaan Kejaksaan RI',
                'deskripsi' => '.',
            //    'created_at' => now(),
             //   'updated_at' => now(),
            ],
            [
                'id_sastra' => '4',
                'id_saspro' => '4.7',
                'nama_saspro' => 'Meningkatnya kualitas kebijakan penegakan hukum',
                'deskripsi' => '.',
            //    'created_at' => now(),
             //   'updated_at' => now(),
            ],
            [
                'id_sastra' => '4',
                'id_saspro' => '4.8',
                'nama_saspro' => 'Meningkatnya kuantitas dan kualitas SDM aparatur Kejaksaan RI',
                'deskripsi' => '.',
            //    'created_at' => now(),
             //   'updated_at' => now(),
            ],
            [
                'id_sastra' => '4',
                'id_saspro' => '4.9',
                'nama_saspro' => 'Meningkatnya kualitas program Pendidikan dan Pelatihan Kejaksaan RI',
                'deskripsi' => '.',
            //    'created_at' => now(),
             //   'updated_at' => now(),
            ],
            [
                'id_sastra' => '4',
                'id_saspro' => '4.10',
                'nama_saspro' => 'Meningkatnya kualitas layanan internal dukungan manajemen dan kesehatan yustisial',
                'deskripsi' => '.',
            //    'created_at' => now(),
             //   'updated_at' => now(),
            ],
            [
                'id_sastra' => '4',
                'id_saspro' => '4.11',
                'nama_saspro' => 'Meningkatnya kompetensi Aparatur Kejaksaan RI',
                'deskripsi' => '.',
            //    'created_at' => now(),
             //   'updated_at' => now(),
            ],
            [
                'id_sastra' => '4',
                'id_saspro' => '4.12',
                'nama_saspro' => 'Meningkatnya Integritas Aparatur Kejaksaan RI',
                'deskripsi' => '.',
            //    'created_at' => now(),
             //   'updated_at' => now(),
            ],
            [
                'id_sastra' => '4',
                'id_saspro' => '4.13',
                'nama_saspro' => 'Meningkatnya Kualitas Layanan Hukum dan Hubungan Luar Negeri',
                'deskripsi' => '.',
            //    'created_at' => now(),
             //   'updated_at' => now(),
            ],
            [
                'id_sastra' => '4',
                'id_saspro' => '4.14',
                'nama_saspro' => 'Menguatnya birokrasi yang bersih, transparan, dan melayani',
                'deskripsi' => '.',
            //    'created_at' => now(),
             //   'updated_at' => now(),
            ],
            [
                'id_sastra' => '4',
                'id_saspro' => '4.15',
                'nama_saspro' => 'Meningkatnya efektivitas pelaksanaan tugas dan fungsi Kejaksaan berbasis TI',
                'deskripsi' => '.',
            //    'created_at' => now(),
             //   'updated_at' => now(),
            ],
            [
                'id_sastra' => '4',
                'id_saspro' => '4.16',
                'nama_saspro' => 'Meningkatnya kuantitas dan kualitas sarana dan prasarana yang mendukung Kinerja Kejaksaan RI',
                'deskripsi' => '.',
            //    'created_at' => now(),
             //   'updated_at' => now(),
            ],
        ]);
    }
}